CREATE TABLE IF NOT EXISTS mpa (
	mpa_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar(5)
);
CREATE TABLE IF NOT EXISTS film (
	film_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	title varchar(50),
	description varchar(200),
	release_date date,
	duration int,
	mpa_id int REFERENCES mpa ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS genre (
	genre_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar(20)
);
CREATE TABLE IF NOT EXISTS film_genre (
	film_id int REFERENCES film ON DELETE CASCADE,
	genre_id int REFERENCES genre ON DELETE CASCADE,
	PRIMARY KEY (film_id, genre_id)
);
CREATE TABLE IF NOT EXISTS users (
	user_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	login varchar(20),
	name varchar(30),
	email varchar(30),
	birthday date
);
CREATE TABLE IF NOT EXISTS user_friend (
	user_id int REFERENCES users ON DELETE CASCADE,
	friend_id int REFERENCES users ON DELETE CASCADE,
	is_accepted boolean,
	PRIMARY KEY (user_id, friend_id)
);
CREATE TABLE IF NOT EXISTS user_like_film (
	film_id int REFERENCES film ON DELETE CASCADE,
	user_id int REFERENCES users ON DELETE CASCADE,
	PRIMARY KEY (film_id, user_id)
);